config/routes.rb
Tagit::Application.routes.draw do


root :to => "projects#index"
resources :projects


  authenticated :user do
    root :to => 'home#index'
  end
  
  root :to => "home#welcome"
  devise_for :users
  resources :users

  resources :tags
  root to: "tags#index"

  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
  
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
#   else
#     can :read, :all
    end
  
  end
  
end

app/models/addvideotoproject.rb
class AddVideoToProject < ActiveRecord::Migration
  def self.up
    add_column :projects, :video_file_name, :string # Original filename
    add_column :projects, :video_content_type, :string # Mime type
    add_column :projects, :video_file_size, :integer # File size in bytes
  end

  def self.down
    remove_column :projects, :video_file_name
    remove_column :projects, :video_content_type
    remove_column :projects, :video_file_size
  end
end

app/models/data_file.rb
class DataFile < ActiveRecord::Base
def self.save(upload)
name = upload['datafile'].original_filename
directory = "public/data"
# create the file path
path = File.join(directory, name)
# write the file
File.open(path, "wb") { |f| f.write(upload['datafile'].read) }
end
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  attr_accessible :goal, :name, :video
  validate :user, :presence => true
  # Paperclip
  has_attached_file :video
 
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  attr_accessible :avatar
  has_attached_file :avatar, :default_url => "/images/:style/missing.png"
 
  after_create :assign_default_role

  def assign_default_role
    add_role(:user)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController 
  def index
    @users = User.all
  end
  
  def welcome
  end
  
  def devise_mapping
      @devise_mapping ||= Devise.mappings[:user]
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def new
	end
end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
def index
render :file => 'app\views\upload\uploadfile.rhtml'
end
def uploadFile
post = DataFile.save(params[:upload])
render :text => "File has been uploaded successfully"
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def create
  @user = User.create( params[:user] )
  end

  def show
    @user = User.find(params[:id])
  end
 
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
   
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/home/index.html.erb
<div id="boxes">

<div id="dialog" class="window">


					
						<a href="#" class="close">[X]</a>
						<legend>Novo Projeto/Video</legend>

						<br />

						<dl>
							<dt><label for="project">Projeto:</label></dt>
							<dd><input type="text" name="project" id="project" cols="60"></textarea></dd>
						</dl>

						<dl>
							<dt><label for="comments">Descrição:</label></dt>
							<dd><textarea name="comments" id="comments" rows="3" width="400px"></textarea></dd>
						</dl>
							
						<dl>
							<dt><label for="comments">Descrição:</label></dt>
							<dd>	<% form_for :project, :html => { :multipart => true } do |f| %>
							  <%= f.file_field :video%>
							<% end %>
							</dd>
						</dl>

						
						<dl>
							<dt><label for="upload">Video:</label></dt>
							<dd><input type="file" name="upload" id="upload" /></dd>
						</dl>

						 <dl>
				            <dd><button class="btn btn-inverse" type="button" name="test" id="test">Criar Projeto</button></dd>
				        </dl>

						
					
</div>
  

<div class="tab-pane" id="navbar-fixed-Organize">
			

	<div >
	        <div id="folders" style="">
	          
	          <ul class="clearfix">
	            <li class="folder new">
	              <a href="#dialog" name="modal" ></a>
	            </li>
	            
	            <li class="folder" data-folderid="13a0b88d7c">
	            <a href="#" data-action="open-folder">
	                <h3 class="folder-name">Tag-It</h3>
	              </a>
	              <div class="bottom clearfix proxima-thin">
	                <div class="left">
	                  Project Description
	                </div>
	                <div class="btn-group dropdown pull-right">
	                  <a class="btn-link dropdown-toggle" data-toggle="dropdown" href="#">
	                    <div class="j-icon j-icon-gear-black"></div>
	                  </a>
	                </div>

	            </li>
	            
	          </ul>
	        </div>
	    </div>
	</div>


    
	</div><!-- /#navbar-fixed-css -->

</div>


<!--<h3>Home</h3><% @users.each do |user| %>
  <p>User: <%=link_to user.name, user %></p>
<% end %>-->

<script type="text/javascript">


$(document).ready(function() {	

	$('a[name=modal]').click(function(e) {
		e.preventDefault();
		
		var id = $(this).attr('href');
	
		var maskHeight = $(document).height();
		var maskWidth = $(window).width();
	
		$('#mask').css({'width':maskWidth,'height':maskHeight});

		$('#mask').fadeIn(1000);	
		$('#mask').fadeTo("slow",0.8);	
	
		//Get the window height and width
		var winH = $(window).height();
		var winW = $(window).width();
              
		//$(id).css('top',  winH/2-$(id).height()/2);
		$(id).css('left', winW/2-$(id).width()/2);
	
		$(id).fadeIn(2000); 
	
	});
	
	$('.window .close').click(function (e) {
		e.preventDefault();
		
		$('#mask').hide();
		$('.window').hide();
	});		
	
	$('#mask').click(function () {
		$(this).hide();
		$('.window').hide();
	});			
	
});

</script>

app/views/home/welcome.html.erb
<!--Not Logged user home screen-->

<link href="css/style.css" rel="stylesheet">

<div class="note-tabs"> <!-- Homepage Tabs-->

	<ul class="nav nav-tabs">
		<li class="active"><a href="#navbar-fixed-Start" data-toggle="tab"><strong>Comece Aqui</strong></a></li>
		<li><a href="#navbar-fixed-Organize" data-toggle="tab"><strong>Organize seus projetos</strong></a></li>
		<li><a href="#navbar-fixed-Tags" data-toggle="tab"><strong>Crie Etiquetas</strong></a></li>
		<li><a href="#navbar-fixed-Consolidate" data-toggle="tab"><strong>Consolide Sua Avaliação</strong></a></li>
	</ul>

	

	<div class="tab-content">

		<!-- Tab 1 - Comece Aqui -->

		<div class="tab-pane active" id="navbar-fixed-Start">
			<iframe class = "tabFrame" src="StartScreen.html"></iframe>
		</div><!-- #navbar-fixed-html -->
		

		<!-- Tab 2 - Meus Projetos -->
		
		<div class="tab-pane" id="navbar-fixed-Organize">
			<iframe class = "tabFrame" src="OrganizeScreen.html"></iframe>
	    </div><!-- /#navbar-fixed-css -->


		<!-- Tab 3 - Etiquetagem -->

		<div class="tab-pane" id="navbar-fixed-Tags">
			<iframe class = "tabFrame"  src="TagScreen.html"></iframe>
	    </div>


		<!-- Tab 4 - Consolidação -->


		<div class="tab-pane" id="navbar-fixed-Consolidate">
			<iframe class = "tabFrame"  src="ConsolidateScreen.html"></iframe>
		</div><!-- /#navbar-fixed-css -->

	</div><!-- .tab-content -->

</div><!-- /.note-tabs -->


	

app/views/layouts/_footer.html.erb
<footer>
	<div id="footer">
		<p class="pull-right"><a href="#">Back to top</a></p>
		<p class="muted"> &copy; Blá blá blá.... 2012</p>	
	</div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-inverse navbar-fixed-top">
	<nav class="navbar-inner">
		<div class="container-fluid">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<%= link_to "Tag-It", root_path, :class => 'brand' %>
			<div class="nav-collapse collapse">
				<div class= "pull-right">
					<% if user_signed_in? %>
					<%= link_to '<i class="icon-signout"></i> Log Out'.html_safe, destroy_user_session_path, :method=>'delete', :class=>'btn btn-small', :title => 'Sair', :rel => 'tooltip' %>
						<% else %>
						<%= link_to '<i class="icon-signin"></i> Entrar'.html_safe, new_user_session_path, :class=>'btn btn-small', :title => 'Signin', :rel => 'tooltip' %>
						<!-- <form class="navbar-form pull-right">
							<input class="span2" type="text" placeholder="Email">
							<input class="span2" type="password" placeholder="Senha">
							<button type="submit" class="btn btn-small" title="Login" rel"tooltip"><i class="icon-signin"></i></button>
						</form> -->
					<% end %>
				</div>
				<ul class="nav">
					<% if user_signed_in? %>
					<li>
						<%= link_to('Editar Conta', edit_user_registration_path) %>
					</li>
					<% if current_user.has_role? :admin %>
					<li>
						<%= link_to('Admin', users_path) %>
					</li>
					<% end %>
					<% else %>
					<li>
						<%= link_to('Registrar', new_user_registration_path)  %>
					</li>
					<% end %>
				</ul>
			</div><!--/.nav-collapse -->
		</div>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap.min.css">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title><%= content_for?(:title) ? yield(:title) : "Tag-It" %></title>
	<meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Tag-It" %>">
	<%= stylesheet_link_tag "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<%= yield(:head) %>
</head>
<body>
	<%= render 'layouts/navigation' %>
	<div id="main" role="main">
		<div class="container">
			<%= render 'layouts/messages' %>
			<div class="content">
				<%= yield %>
			</dv>
		</div>
	</div>
</body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>


<%= form_for(Project.new, :html => { :class => 'form-vertical', :multipart => true }) do |f| %>
   <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :goal %><br>
    <%= f.text_area :goal %>
  </p>

  <%= f.file_field :video %>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>


<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/tags/index.html.erb
<h3>Home</h3><% @users.each do |user| %>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline' %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h3>Users</h3>
<table class="table table-condensed">
  <thead>
      <tr>
          <th>Username</th>
          <th>Email</th>
          <th>Registered</th>
          <th>Role</th>
          <th></th>
          <th></th>                                     
      </tr>
  </thead>  
  <tbody>
  <% @users.each do |user| %>
    <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at.to_date %></td>
        <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
        <td>
          <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
          <%= render user %>
        </td>
        <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>                                       
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<h3>User</h3><p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>